---
algorithm: "Continuous Skill Space"
version: "latent split seq | guided | sac in feature space | rnn only"
layer_size: 256
replay_buffer_size: 10000

env_kwargs:
  env_id: two_d_nav
  exclude_current_positions_from_observation: False

obs_dims_used_policy_all_except: null

algorithm_kwargs:
  num_epochs: 1000
  num_eval_steps_per_epoch: 1000
  num_trains_per_train_loop: 600
  num_expl_steps_per_train_loop: 10
  min_num_steps_before_training: 200
  max_path_length: 1000
  batch_size: 350

trainer_kwargs:
  discount: 0.99
  soft_target_tau: 0.005
  target_update_period: 1
  policy_lr: 0.0003
  qf_lr: 0.0003
  reward_scale: 1
  use_automatic_entropy_tuning: True
  df_lr: 0.001
  train_sac_in_feature_space: True

seq_len: 5
horizon_len: 60
seq_eval_len: 5
horizon_eval_len: 60
skill_dim: 2

info_loss:
  alpha: 0.8
  lamda: 0.1

test_script_path: [/home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_plot.py,
                   /home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_render.py]
log_folder: logstwodnav
log_interval: 10
