---
algorithm: "Continuous Skill Space"
version: "latent split seq | guided | sac in feature space | rnn only"
layer_size: 256
replay_buffer_size: 100000
random_hp_tuning: True

env_kwargs:
  env_id: hopper
  exclude_current_positions_from_observation: False

obs_dims_used_policy_all_except: [0, ]

algorithm_kwargs:
  num_epochs: 500
  num_eval_steps_per_epoch: 1000
  num_trains_per_train_loop: 200
  num_expl_steps_per_train_loop: 5
  min_num_steps_before_training: 400
  max_path_length: 1000
  obs_dims_to_log: [0, 1, 2]
  batch_size: 1000

trainer_kwargs:
  discount: 0.99
  soft_target_tau: 0.005
  target_update_period: 1
  policy_lr: 0.0003
  qf_lr: 0.0003
  reward_scale: 1
  use_automatic_entropy_tuning: True
  df_lr: 0.001
  train_sac_in_feature_space: True

seq_len: 20
horizon_len: null
seq_eval_len: null
horizon_eval_len: null
skill_dim: 2

info_loss:
  alpha: 0.5
  lamda: 0.0

df_type:
  feature_extractor: rnn
  rnn_type: normal
  latent_type: full_seq
  recon: end_only

latent_kwargs:
  None: null

latent_kwargs_smoothing:
  None: null

latent_single_layer_kwargs:
  None: null

rnn_kwargs:
  hidden_size_rnn: 1
  bidirectional: False

df_kwargs_rnn:
  obs_dims_used: null
  obs_dims_used_except: [0, ]
  dropout: 0.0
  leaky_slope_classifier: 0.1
  hidden_units_classifier: null
  std_classifier: null

df_kwargs_latent:
  None: null

test_script_path: [/home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_plot.py,
                   /home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_render.py]
log_folder: logshopper
log_interval: 5
