---
EnvKwargs:
  gym_id: MountainCarContinuous-v0
  action_repeat: 1
  normalize_states: True

TrainerKwargs:
  discount: 0.99
  soft_target_tau: 5e-3
  target_update_period: 1
  policy_lr: 3E-4
  qf_lr: 3E-4
  reward_scale: 1
  use_automatic_entropy_tuning: True

AlgoKwargs:
  batch_size: 64
  num_epochs: 1000
  seq_len: 70
  num_eval_steps_per_epoch: 200
  num_expl_steps_per_train_loop: 1
  num_trains_per_train_loop: 10
  num_train_loops_per_epoch: 1
  min_num_steps_before_training: 10

Other:
  algorithm: Self Supervised
  version: 0.0.1
  hidden_layer: [256, 256]
  replay_buffer_size: 1000000
  skill_dim: 2
  layer_norm: True
