---
algorithm: "Continuous Skill Space"
version: "latent split seq | guided | sac in feature space | rnn only"
layer_size: 256
replay_buffer_size: 100000
random_hp_tuning: True

env_kwargs:
  env_id: MountainCarContinuous-v0
  exclude_current_positions_from_observation: False

obs_dims_used_policy_all_except: null

algorithm_kwargs:
  num_epochs: 500
  num_eval_steps_per_epoch: 1000
  num_trains_per_train_loop: 100
  num_expl_steps_per_train_loop: 5
  min_num_steps_before_training: 400
  max_path_length: 1000
  batch_size: 1000

trainer_kwargs:
  discount: 0.99
  soft_target_tau: 0.005
  target_update_period: 1
  policy_lr: 0.0003
  qf_lr: 0.0003
  reward_scale: 1
  use_automatic_entropy_tuning: True
  df_lr: 0.001
  train_sac_in_feature_space: True

seq_len: 5
horizon_len: 100
skill_dim: 2

df_evaluation_env:
  obs_dims_to_log: [0, 1]
  action_dims_to_log: [0,]
  seq_len: 25
  horizon_len: 100
  plot_skill_influence:
    obs: True
    action: True
    obs_one_plot: True
    plot_post: True

df_evaluation_memory:
  seq_len: 25
  horizon_len: 100
  batch_size: 100

info_loss:
  alpha: 0.1
  lamda: 0.0

df_type:
  feature_extractor: srnn
  rnn_type: normal
  latent_type: full_seq
  recon: whole_seq

latent_kwargs:
  None: null

latent_kwargs_smoothing:
  None: null

latent_single_layer_kwargs:
  None: null

rnn_kwargs: null

srnn_kwargs:
  rnn_kwargs:
    hidden_size_rnn: 5
    bidirectional: False
  stoch_latent_kwargs:
    latent1_dim: 1
    latent2_dim: 4
    hidden_units: [128, 128]
    leaky_slope: 0.2
    dropout: 0.0
    beta_anneal:
      start: 0.2
      add: 0.00003
      end: 1
  filter_net_params: null

df_kwargs_rnn: null

df_kwargs_srnn:
  obs_dims_used: null
  obs_dims_used_except: null
  dropout: 0.0
  leaky_slope_classifier: 0.2
  hidden_units_classifier: [200, 200]
  std_classifier: null

df_kwargs_latent:
  None: null

test_script_path: [/home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_plot.py,
                   /home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_render.py]
log_folder: logs/mountaincar
log_interval: 10
