---
algorithm: "Continuous Skill Space"
version: "latent split seq | guided | sac in feature space | rnn only"
random_hp_tuning: False
layer_size: 256
replay_buffer_size: 10000

env_kwargs:
  env_id: halfcheetah
  exclude_current_positions_from_observation: False

obs_dims_used_policy_all_except: null

algorithm_kwargs:
  num_epochs: 200
  num_eval_steps_per_epoch: 1000
  num_trains_per_train_loop: 557
  num_expl_steps_per_train_loop: 10
  min_num_steps_before_training: 200
  max_path_length: 1000
  batch_size: 447

trainer_kwargs:
  discount: 0.99
  soft_target_tau: 0.005
  target_update_period: 1
  policy_lr: 0.0003
  qf_lr: 0.0003
  reward_scale: 1
  use_automatic_entropy_tuning: True
  df_lr: 0.001
  train_sac_in_feature_space: False

srnn_kwargs:
  stoch_latent_kwargs:
    latent_dim: 100
    dropout: 0.22
    beta_anneal:
      start: 0.2
      add: 0.000054
      end: 1
    res_q_posterior: True
  det_latent_kwargs:
    hidden_size_rnn: 5
  filter_net_params: null

df_kwargs:
  std_classifier: 1.
  dropout_classifier: 0.161

seq_len: 15
horizon_len: 63
seq_eval_len: 15
horizon_eval_len: 63
skill_dim: 2

info_loss:
  alpha: 1.00
  lamda: 0.0

test_script_path: [/home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_plot.py,
                   /home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_render.py]
log_folder: logshalfcheetah_srnn
log_interval: 2
