---
algorithm: "Continuous Skill Space"
version: "latent split seq | guided | sac in feature space | rnn only"
layer_size: 256
replay_buffer_size: 100000
random_hp_tuning: False

env_kwargs:
  env_id: swimmer
  exclude_current_positions_from_observation: False

obs_dims_used_policy_all_except: [0, 1]

algorithm_kwargs:
  num_epochs: 1000
  num_eval_steps_per_epoch: 1000
  num_trains_per_train_loop: 20
  num_expl_steps_per_train_loop: 10
  min_num_steps_before_training: 400
  max_path_length: 1000
  batch_size: 700

trainer_kwargs:
  discount: 0.99
  soft_target_tau: 0.005
  target_update_period: 1
  policy_lr: 0.0003
  qf_lr: 0.0003
  reward_scale: 1
  use_automatic_entropy_tuning: True
  df_lr: 0.001
  train_sac_in_feature_space: False
  full_seq_sac_training: False

seq_len: 5
horizon_len: 500
seq_eval_len: 5
horizon_eval_len: 500
skill_dim: 2

info_loss:
  alpha: 1.0
  lamda: 0.0

df_type:
  feature_extractor: latent_slac
  rnn_type: normal
  latent_type: full_seq
  recon: end_only

latent_kwargs:
  latent1_dim: 2
  latent2_dim: 8
  hidden_units: [256, 256]
  leaky_slope: 0.2
  dropout: 0.3
  beta_anneal:
    start: 0.2
    add: 0.00003
    end: 1

latent_kwargs_smoothing:
  None: null

latent_single_layer_kwargs:
  None: null

rnn_kwargs:
  hidden_size_rnn: 10
  bidirectional: False

df_kwargs_rnn:
  obs_dims_used: [0, 1]
  dropout: 0.4
  leaky_slope_classifier: 0.2
  hidden_units_classifier: [256, 256]
  std_classifier: 0.5

df_kwargs_latent:
  obs_dims_used: [0, 1]
  hidden_units_classifier: [256, 256]
  leaky_slope_classifier: 0.2
  classifier_dropout: 0.5
  classifier_std: null

test_script_path: [/home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_plot.py,
                   /home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_render.py]
log_folder: logsswimmer
log_interval: 10
