---
algorithm: "Continuous Skill Space"
version: "latent split seq | guided | sac in feature space | rnn only"
random_hp_tuning: True
layer_size: 256
replay_buffer_size: 10000

env_kwargs:
  env_id: MountainCarContinuous-v0
  exclude_current_positions_from_observation: False

obs_dims_used_policy_all_except: null

algorithm_kwargs:
  num_epochs: 200
  num_eval_steps_per_epoch: 1000
  num_trains_per_train_loop: 300
  num_expl_steps_per_train_loop: 10
  min_num_steps_before_training: 200
  max_path_length: 1000
  batch_size: 200

trainer_kwargs:
  discount: 0.99
  soft_target_tau: 0.005
  target_update_period: 1
  policy_lr: 0.0003
  qf_lr: 0.0003
  reward_scale: 1
  use_automatic_entropy_tuning: True
  df_lr: 0.0001
  train_sac_in_feature_space: True

srnn_kwargs:
  stoch_latent_kwargs:
    latent1_dim: 2
    latent2_dim: null
    dropout: 0.2
    beta_anneal:
      start: 0.2
      add: 0.00001
      end: 1
  det_latent_kwargs:
    hidden_size_rnn: 3
  filter_net_params: null

df_kwargs:
  std_classifier: 0.5
  dropout_classifier: 0.

seq_len: 2
horizon_len: 90
seq_eval_len: 2
horizon_eval_len: 90
skill_dim: 2

info_loss:
  alpha: 0.9
  lamda: 0.1

test_script_path: [/home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_plot.py,
                   /home/michael/EIT/Github_Repos/24_SelfSupervisedDevel/cont_skillspace_test/main_test_guided_normal_render.py]
log_folder: logsmountaincar_srnn
log_interval: 2
